### ISSUE TITLE
Use credential secrets instead of storing user/pass in spec

### ISSUE THREAD

**Issue by kasey** [crossplane-contrib/provider-terraform-vsphere#2]
Using the spec was a quick hack so I didn't have to spend time on the providerconfig->terraform initialization, should be an easy task to convert it to use credential secrets like other providers.

**Comment by kasey** [comment]
This is a little wonky - I used the basic-auth k8s Secret Type[1] but the structure of the secretRef still requires a Key field to be specified. Need to chat with the team about this -- When dealing with user+pass pairs, it would be nice to use the basic-auth's more readable structure rather than double-encode a json value in a key of the secret or something like that.

[1] https://kubernetes.io/docs/concepts/configuration/secret/#basic-authentication-secret

**Comment by kasey** [comment]
to minimize difference with other providers I switched to storing only the password in a secret, which maintains the model of a secret ref having a required key field. example:
```
apiVersion: vsphere.terraform-plugin.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: vsphere-provider
spec:
  user: user
  password: pass
  allow_unverified_ssl: true
  vsphere_server: "127.0.0.1:30443"
  credentials:
    source: Secret
    secretRef:
      name: vsphere-pass
      namespace: default
      key: password
---
apiVersion: v1
kind: Secret
metadata:
  name: vsphere-pass
type: Opaque
data:
  password: pass
```
